const RAW_SEED_STORIES: any[] = [
  {
    "id": "S01",
    "headline": "Register account",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Register",
    "capability": "Onboarding",
    "integration": "S3 / Storage",
    "status": "",
    "seq": "1.0",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S02",
    "headline": "Fill contact & company details",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Register",
    "capability": "Onboarding",
    "integration": "S3 / Storage",
    "status": "",
    "seq": "2.0",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S03",
    "headline": "Upload documents",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Register",
    "capability": "Onboarding",
    "integration": "S3 / Storage",
    "status": "",
    "seq": "3.0",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S04",
    "headline": "Resubmit onboarding documents after rejection",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Register",
    "capability": "Onboarding",
    "integration": "Email / SMTP, S3 / Storage",
    "status": "",
    "seq": "6.0",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S05",
    "headline": "Log In to seller Portal",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "Email / SMTP, SSO",
    "status": "",
    "seq": "9.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S06",
    "headline": "Setup banking",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "12.0",
    "pts": 0.25,
    "size": "0.25",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S07",
    "headline": "Update bank details after Finance rejection",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "Email / SMTP",
    "status": "",
    "seq": "",
    "pts": 0.25,
    "size": "0.25",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S08",
    "headline": "Set shipping method",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "14.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S09",
    "headline": "Upload shop identity",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "S3 / Storage",
    "status": "",
    "seq": "14.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S10",
    "headline": "Set return address & policy",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "14.0",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S11",
    "headline": "Accept terms and go live",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "PandaDoc, S3 / Storage",
    "status": "",
    "seq": "14.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S12",
    "headline": "Setup shop operating region",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "14.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S13",
    "headline": "Create product",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Create offers",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 5.0,
    "size": "5.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S14",
    "headline": "Create product bundle",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Create offers",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S15",
    "headline": "Bulk upload products",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Create offers",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 4.0,
    "size": "4.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S16",
    "headline": "Update stock",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage stock",
    "capability": "Inventory",
    "integration": "CIS (Inventory), RMS",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S17",
    "headline": "Setup pre-order",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage stock",
    "capability": "Inventory",
    "integration": "CIS (Inventory), RMS",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S18",
    "headline": "Edit price or stock",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage price",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S19",
    "headline": "Bulk update prices",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage price",
    "capability": "Product Setup",
    "integration": "RM3, RMS, Product Service",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S20",
    "headline": "Edit product details",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage product",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S21",
    "headline": "Add or edit variants",
    "persona": "Seller",
    "goal": "Q1",
    "action": "Manage product",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S22",
    "headline": "Bulk upload variants",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage product",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S23",
    "headline": "Toggle product status",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage product",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 0.25,
    "size": "0.25",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S24",
    "headline": "Delete single product",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage product",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 0,
    "size": "\u2014",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S25",
    "headline": "View Products",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage product",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S26",
    "headline": "Bulk delete products",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage product",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S27",
    "headline": "View Promotions",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Manage promotions",
    "capability": "Promotions",
    "integration": "Loyalty System, RM3",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S28",
    "headline": "Create Buy and Get Promtions",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Manage promotions",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S29",
    "headline": "Create Buy and Get on Y promotions",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Manage promotions",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S30",
    "headline": "Create Simple Promotions",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Manage promotions",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S31",
    "headline": "Create a ribbon configuration",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Manage promotions",
    "capability": "Promotions",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S32",
    "headline": "Create Shipping Promotion",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Manage promotions",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S33",
    "headline": "Join promo campaign",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Enrol into campaigns",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S34",
    "headline": "Join loyalty campaign",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Enrol into campaigns",
    "capability": "Promotions",
    "integration": "Loyalty System, RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S35",
    "headline": "View and manage active discounts",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Manage discounts",
    "capability": "Promotions",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S36",
    "headline": "Enrol in Gold Container / Flash Sale campaign",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Enrol into campaigns",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S37",
    "headline": "Enable Payment on Delivery",
    "persona": "Seller",
    "goal": "Setup Payments",
    "action": "Configure POD",
    "capability": "Payments",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S38",
    "headline": "Configure installments",
    "persona": "Seller",
    "goal": "Setup Payments",
    "action": "Enable installments",
    "capability": "Payments",
    "integration": "AO (Axtra Omni)",
    "status": "Delete",
    "seq": "",
    "pts": 0,
    "size": "\u2014",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S39",
    "headline": "View and accept SOD order",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S40",
    "headline": "Update SOD order to shipped",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S41",
    "headline": "Upload delivery summary",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S42",
    "headline": "Upload invoice",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S43",
    "headline": "Prepare dropship order",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S44",
    "headline": "Print delivery note and airway bills",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S45",
    "headline": "Cancel order",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S46",
    "headline": "Handle customer-initiated order cancellation",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni), Email / SMTP",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S47",
    "headline": "Accept or reject return",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage returns",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S48",
    "headline": "Inspect return and process refund",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage returns",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni), DHL / Flash Express",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S49",
    "headline": "Configure SOD fleet and costs",
    "persona": "Seller",
    "goal": "Configure Fulfilment",
    "action": "Configure shipping fleet",
    "capability": "Shipping",
    "integration": "AO (Axtra Omni), DHL / Flash Express",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S50",
    "headline": "Select dropship fleet",
    "persona": "Seller",
    "goal": "Configure Fulfilment",
    "action": "Configure shipping fleet",
    "capability": "Shipping",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S51",
    "headline": "Add and manage warehouse",
    "persona": "Seller",
    "goal": "Configure Fulfilment",
    "action": "Configure warehouse",
    "capability": "Onboarding",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "14.0",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S52",
    "headline": "Setup delivery regions and coverage",
    "persona": "Seller",
    "goal": "Configure Fulfilment",
    "action": "Configure shop service area",
    "capability": "Onboarding",
    "integration": "Loyalty System",
    "status": "",
    "seq": "14.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S53",
    "headline": "View order and return dashboards",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "Loyalty System",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S54",
    "headline": "View promotions and campaigns dashboards",
    "persona": "Seller",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage Promotions",
    "capability": "Shop Operations",
    "integration": "Loyalty System",
    "status": "",
    "seq": "",
    "pts": 4.0,
    "size": "4.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S55",
    "headline": "View income and finance reports",
    "persona": "Seller",
    "goal": "Get Insights",
    "action": "View income",
    "capability": "Shop Operations",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S56",
    "headline": "Set shop on vacation",
    "persona": "Seller",
    "goal": "Manage Shop",
    "action": "Set shop on vacation",
    "capability": "Seller Governance",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 0.2,
    "size": "0.2",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S57",
    "headline": "Manage shop team and user access",
    "persona": "Seller",
    "goal": "Manage Shop",
    "action": "Manage users",
    "capability": "Platform Operations",
    "integration": "Email / SMTP",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S58",
    "headline": "View notifications by module",
    "persona": "Seller",
    "goal": "Manage Shop",
    "action": "Manage users",
    "capability": "Platform Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 3.5,
    "size": "3.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S59",
    "headline": "Set language preference",
    "persona": "Seller",
    "goal": "My Profile",
    "action": "Set language preference",
    "capability": "Platform Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S60",
    "headline": "Reset my password",
    "persona": "Seller",
    "goal": "My Profile",
    "action": "Reset my password",
    "capability": "Platform Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S61",
    "headline": "Generate API key",
    "persona": "Seller",
    "goal": "My Profile",
    "action": "Generate API key",
    "capability": "Platform Operations",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 0.25,
    "size": "0.25",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S62",
    "headline": "Search self-help",
    "persona": "Seller",
    "goal": "Support",
    "action": "Get support",
    "capability": "Onboarding",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 3.0,
    "size": "3.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S63",
    "headline": "Contact operator for support",
    "persona": "Seller",
    "goal": "Support",
    "action": "Get support",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 0,
    "size": "\u2014",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S64",
    "headline": "View category taxes (read only)",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S65",
    "headline": "Clone Shoppee Product via excel",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Create offers",
    "capability": "Product Setup",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S66",
    "headline": "Upload additional Documents",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "10.0",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S67",
    "headline": "esign the Contract and upload",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "11.0",
    "pts": 3.0,
    "size": "3.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S68",
    "headline": "Select shipping method per product",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Create offers",
    "capability": "Product Setup",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S69",
    "headline": "Seller Dashboard",
    "persona": "Seller",
    "goal": "Register & Setup Shop",
    "action": "Setup shop",
    "capability": "Shop Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S70",
    "headline": "Seller Order Notification",
    "persona": "Seller",
    "goal": "Manage Orders & Returns",
    "action": "Manage orders",
    "capability": "Order Fulfillment",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S71",
    "headline": "Bulk Upload stock",
    "persona": "Seller",
    "goal": "Manage Offers",
    "action": "Manage Stock",
    "capability": "Order Fulfillment",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 1.5,
    "size": "1.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S72",
    "headline": "Bulk tag products to Promotions & Campaigns",
    "persona": "Seller",
    "goal": "Run Promotions & Campaigns",
    "action": "Adding Bulk Products",
    "capability": "Promotions",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "S73",
    "headline": "See Product Versioning",
    "persona": "Seller",
    "goal": "Manage offers",
    "action": "Manage product",
    "capability": "Product Setup",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 0,
    "size": "\u2014",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O01",
    "headline": "Operator login",
    "persona": "Operator",
    "goal": "Manage Platform",
    "action": "Manage Roles & access",
    "capability": "Platform Operations",
    "integration": "SSO / Identity Provider (CP Axtra), Email / SMTP",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O03",
    "headline": "View List of sellers pending approval",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "S3 / Storage",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O04",
    "headline": "Validate seller documents",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "Email / SMTP, PandaDoc, S3 / Storage",
    "status": "",
    "seq": "4.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O05",
    "headline": "Request additional documents",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "5.0",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O06",
    "headline": "Review delta changes on seller re-submission",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "Email / SMTP, S3 / Storage",
    "status": "",
    "seq": "7.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O07",
    "headline": "Approve or reject seller",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "8.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O08",
    "headline": "Finance L1 approval",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "14.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O09",
    "headline": "Finance L2 approval",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "15.0",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O10",
    "headline": "Approve and activate shop",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "Email / SMTP,",
    "status": "",
    "seq": "13.0",
    "pts": 0.2,
    "size": "0.2",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O11",
    "headline": "Download seller documents",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "Email / SMTP",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O12",
    "headline": "Notify seller of approval status",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "Email / SMTP,",
    "status": "",
    "seq": "16.0",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O13",
    "headline": "Set seller vacation or suspension",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Manage seller",
    "capability": "Seller Governance",
    "integration": "Email / SMTP",
    "status": "",
    "seq": "",
    "pts": 0.2,
    "size": "0.2",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O14",
    "headline": "Disable seller",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Manage seller",
    "capability": "Seller Governance",
    "integration": "CIS (Inventory), RM3, RMS, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 0.2,
    "size": "0.2",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O15",
    "headline": "Enable seller",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Manage seller",
    "capability": "Seller Governance",
    "integration": "CIS (Inventory), RM3, RMS, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 0.2,
    "size": "0.2",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O16",
    "headline": "View list of products by status brand seller",
    "persona": "Operator",
    "goal": "Manage Product & Catalog",
    "action": "Manage products",
    "capability": "Product Setup",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O17",
    "headline": "Approve or reject products",
    "persona": "Operator",
    "goal": "Manage Product & Catalog",
    "action": "Manage products",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O18",
    "headline": "Toggle product status",
    "persona": "Operator",
    "goal": "Manage Product & Catalog",
    "action": "Manage products",
    "capability": "Seller Governance",
    "integration": "Email / SMTP, Location service, PandaDoc, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 0.25,
    "size": "0.25",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O19",
    "headline": "Bulk delete products",
    "persona": "Operator",
    "goal": "Manage Product & Catalog",
    "action": "Manage products",
    "capability": "Product Setup",
    "integration": "CIS (Inventory), RM3, RMS, S3 / Storage, eCommerce / Product Service",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O20",
    "headline": "Enable restricted category",
    "persona": "Operator",
    "goal": "Manage Product & Catalog",
    "action": "Manage category attributes",
    "capability": "Seller Governance",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O21",
    "headline": "Manage category attributes",
    "persona": "Operator",
    "goal": "Manage Product & Catalog",
    "action": "Manage category attributes",
    "capability": "Product Setup",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O22",
    "headline": "List the promo campaign",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage promo campaign",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O23",
    "headline": "Create promo campaign",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage promo campaign",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O24",
    "headline": "Approve products and select carousel",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage promo campaign",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O25",
    "headline": "Download campaign Excel",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage promo campaign",
    "capability": "Promotions",
    "integration": "Loyalty System, RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O26",
    "headline": "Create instant discount",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage instant discount",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O27",
    "headline": "Create loyalty Pro Point campaign",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage loyalty campaign",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O28",
    "headline": "Create gold container / flash sale campaign",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage gold container",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O29",
    "headline": "Reconcile campaign seller accounts",
    "persona": "Operator",
    "goal": "Get Insights",
    "action": "View promotion reports",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 3.0,
    "size": "3.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O30",
    "headline": "View promotion reports",
    "persona": "Operator",
    "goal": "Get Insights",
    "action": "View promotion reports",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O31",
    "headline": "Set global disbursement cycle",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Manage Disbursement",
    "capability": "Finance & Reporting",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O32",
    "headline": "View settlement dashboard",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Manage Disbursement",
    "capability": "Financial Operations",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 4.0,
    "size": "4.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O33",
    "headline": "Mark payout done",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Manage Disbursement",
    "capability": "Financial Operations",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O34",
    "headline": "Generate and download seller invoice",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Manage Disbursement",
    "capability": "Financial Operations",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O35",
    "headline": "Generate settlement report",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Manage Disbursement",
    "capability": "Financial Operations",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O36",
    "headline": "Disable POD for sellers",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Disable POD for sellers",
    "capability": "Payments",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O37",
    "headline": "Set global commissions per category",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Setup commissions",
    "capability": "Finance & Reporting",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O38",
    "headline": "Set seller-specific commissions",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Setup commissions",
    "capability": "Finance & Reporting",
    "integration": "AO (Axtra Omni), DHL / Flash Express",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O39",
    "headline": "View and edit category taxes",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Setup category taxes",
    "capability": "Finance & Reporting",
    "integration": "AO (Axtra Omni), DHL / Flash Express",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O40",
    "headline": "Configure delivery methods",
    "persona": "Operator",
    "goal": "Configure Fulfilment",
    "action": "Configure delivery methods",
    "capability": "Shipping",
    "integration": "AO (Axtra Omni), DHL / Flash Express",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O41",
    "headline": "Configure 3PL providers",
    "persona": "Operator",
    "goal": "Configure Fulfilment",
    "action": "Configure 3PL providers",
    "capability": "Shipping",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O42",
    "headline": "Configure seller shipping exceptions",
    "persona": "Operator",
    "goal": "Configure Fulfilment",
    "action": "Configure seller exceptions",
    "capability": "Shipping",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O43",
    "headline": "Override pending return approvals",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage returns",
    "capability": "Order Fulfillment",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O44",
    "headline": "Manage return inspection overrides",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage returns",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni), Email/SMTP",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O45",
    "headline": "Configure return rulesets",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage returns",
    "capability": "Seller Governance",
    "integration": "AO (Axtra Omni), Email/SMTP",
    "status": "",
    "seq": "",
    "pts": 3.0,
    "size": "3.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O46",
    "headline": "Override pending-approval orders",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage Orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 0.25,
    "size": "0.25",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O47",
    "headline": "Override pending-shipment orders",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage Orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni), Email/SMTP",
    "status": "",
    "seq": "",
    "pts": 0.25,
    "size": "0.25",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O48",
    "headline": "Operator adding extra insurance to be applied to order",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage Orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni), Email/SMTP",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O49",
    "headline": "Override pending-delivery orders",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage Orders",
    "capability": "Order Fulfillment",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O50",
    "headline": "Approve SOD delivery summary",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage Orders",
    "capability": "Order Fulfillment",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O51",
    "headline": "Enter seller mode",
    "persona": "Operator",
    "goal": "Manage Platform",
    "action": "View Seller mode",
    "capability": "Platform Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 1.5,
    "size": "1.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O52",
    "headline": "Exit seller mode",
    "persona": "Operator",
    "goal": "Manage Platform",
    "action": "View Seller mode",
    "capability": "Platform Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O53",
    "headline": "Create platform roles and assign access",
    "persona": "Operator",
    "goal": "Manage Platform",
    "action": "Manage Roles & access",
    "capability": "Platform Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O54",
    "headline": "Generate API keys for ourselves",
    "persona": "Operator",
    "goal": "Manage Platform",
    "action": "Manage Roles & access",
    "capability": "Platform Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 0.25,
    "size": "0.25",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O55",
    "headline": "Download audit logs",
    "persona": "Operator",
    "goal": "Manage Platform",
    "action": "Manage Roles & access",
    "capability": "Platform Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O56",
    "headline": "Set language preference",
    "persona": "Operator",
    "goal": "My Profile",
    "action": "Set language preference",
    "capability": "Platform Operations",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O57",
    "headline": "Reset my password",
    "persona": "Operator",
    "goal": "My Profile",
    "action": "Reset my password",
    "capability": "Platform Operations",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O58",
    "headline": "View promotions and campaigns dashboard",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "View promotions dashboard",
    "capability": "Financial Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O59",
    "headline": "View order reports",
    "persona": "Operator",
    "goal": "Get Insights",
    "action": "View order reports",
    "capability": "Financial Operations",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O60",
    "headline": "Indicate that seller brand page is live",
    "persona": "Operator",
    "goal": "Register & Setup Shop",
    "action": "Manage seller",
    "capability": "Onboarding",
    "integration": "CMS / Content Management",
    "status": "",
    "seq": "17.0",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O61",
    "headline": "Adjust seller settlement for Makro Points",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Adjust settlement",
    "capability": "Platform Operations",
    "integration": "Finance / Settlement Engine",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O62",
    "headline": "Adjust seller settlement for shipping insurance",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Adjust settlement",
    "capability": "Platform Operations",
    "integration": "Finance / Settlement Engine",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O63",
    "headline": "Upload invoice for settlement adjustment",
    "persona": "Operator",
    "goal": "Manage Accounting",
    "action": "Adjust settlement",
    "capability": "Platform Operations",
    "integration": "Finance / Settlement Engine, S3 / Storage",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O64",
    "headline": "View adjusted settlement report",
    "persona": "Operator",
    "goal": "Review settlement adjustments",
    "action": "Upload",
    "capability": "Platform Operations",
    "integration": "Finance / Settlement Engine",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O65",
    "headline": "Approve or reject pending orders",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage Orders",
    "capability": "Order Fulfillment",
    "integration": "AO (Axtra Omni)",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O66",
    "headline": "Manage promo campaign",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage promo campaign",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O67",
    "headline": "Manage loyalty campaign",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage loyalty campaign",
    "capability": "Promotions",
    "integration": "RM3, Loyalty System",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O68",
    "headline": "Manage Gold Container / Flash Sale campaign",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage gold container",
    "capability": "Promotions",
    "integration": "RM3",
    "status": "",
    "seq": "",
    "pts": 0.5,
    "size": "0.5",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O69",
    "headline": "Operator-Seller's onboarding dashboard",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Manage seller",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O70",
    "headline": "Operator Login Dashboard",
    "persona": "Operator",
    "goal": "Onboard & Manage Sellers",
    "action": "Onboard  sellers",
    "capability": "Onboarding",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O71",
    "headline": "Operator Order and Return Dashbaord",
    "persona": "Operator",
    "goal": "Get Insights",
    "action": "View order reports",
    "capability": "Order Fulfillment",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O72",
    "headline": "Operator updates order to shipped",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage Orders",
    "capability": "Order Fulfillment",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O73",
    "headline": "Operator updates order to Delivered",
    "persona": "Operator",
    "goal": "Manage Orders & Returns",
    "action": "Manage Orders",
    "capability": "",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 2.0,
    "size": "2.0",
    "sprint": "backlog",
    "stream": "backlog"
  },
  {
    "id": "O74",
    "headline": "Mass approve seller in the campaigna",
    "persona": "Operator",
    "goal": "Manage Promotions & Campaigns",
    "action": "Manage bulk Approval",
    "capability": "Promotions",
    "integration": "",
    "status": "",
    "seq": "",
    "pts": 1.0,
    "size": "1.0",
    "sprint": "backlog",
    "stream": "backlog"
  }
]

// Feature 3: Filter out stories with status "delete" or "deleted"
export const SEED_STORIES: any[] = RAW_SEED_STORIES.filter(
  s => !s.status || !['delete', 'deleted'].includes(String(s.status).toLowerCase().trim())
)
